# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kaltmiete', models.PositiveSmallIntegerField(verbose_name='Kaltmiete')),
                ('groesse', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Größe')),
                ('plz', models.PositiveIntegerField(verbose_name='Postleitzahl')),
                ('stadtbezirk', models.CharField(max_length=30, verbose_name='stadtbezirk')),
                ('added', models.DateTimeField(auto_now_add=True, verbose_name='hinzugefügt')),
                ('bewohner', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bewohner')),
                ('abschluss', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jahr des Abschlusses des Mietvertrags')),
                ('erhoehung', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Jahr der letzten Mieterhöhung')),
                ('vermieter', models.CharField(blank=True, choices=[('NP', 'gemeinnützig'), ('PR', 'privat'), ('CO', 'Unternehmen')], max_length=2, verbose_name='Vermieter')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail für Benachrichtigung über Ergebnis')),
                ('ipaddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresse')),
            ],
            options={
                'verbose_name_plural': 'Mieten',
            },
        ),
    ]
